# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shorkCut_challange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shorkCut_challange
 pod 'TinyConstraints'
 pod 'SwiftLint' 
  target 'shorkCut_challangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shorkCut_challangeUITests' do
    # Pods for testing
  end

end
